### ISSUE TITLE
support stdin/stdout ?

### ISSUE THREAD

**Issue by devZer0** [shodanshok/blocksync#2]
would it be possible to have support for stdin/stdout with blocksync ?

using "-" as filename does not seem to work

this would be useful, because for example with borg backup you could avoid fuse mounting the borg archive to access the archive and use borg extract directly, for example

borg extract --stdout /mnt/repo1::sda_07_10_2022 | blocksync.py - localhost /dev/sdc

**Comment by shodanshok** [comment]
I added preliminary support for stdin, syntax is the same you posted above. 
Example: `cat /tmp/1 | ./blocksync.py - localhost /tmp/2`

Adding support for stdout is more problematic, and I am not sure about the use case...

**Comment by devZer0** [comment]
fantastic, thanks!
