### ISSUE TITLE
Python2 EOL

### ISSUE THREAD

**Issue by devZer0** [shodanshok/blocksync#5]
Python2 is EOL for a while ( https://www.python.org/doc/sunset-python-2/ ) , what about porting blocksync to Pyhton3 ?  (did not have a look yet, how difficult that would be)

**Comment by shodanshok** [comment]
Hi, I have a python3 enabled branch that you can find here: https://github.com/shodanshok/blocksync/tree/python3

However, keep in mind that it is less tested at the moment (I have plenty of CentOS 7 and 8 machine where python2 is still available and supported).

**Comment by devZer0** [comment]
ah cool, thanks, i will have a look and test it

**Comment by devZer0** [comment]
it seems it does not work. i have opened another issue. thanks.

**Comment by devZer0** [comment]
>However, keep in mind that it is less tested at the moment (I have plenty of CentOS 7 and 8 machine where python2 is still available and supported).

yes, it's not a big problem

**Comment by shodanshok** [comment]
Thanks for opening a specific issue, I'm closing this one.
